apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: gym-dev
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: apache/kafka:3.8.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: external
              containerPort: 9092
            - name: internal
              containerPort: 29092
            - name: controller
              containerPort: 9093
          envFrom:
            - configMapRef:
                name: kafka-config
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          volumeMounts:
            - name: kafka-data
              mountPath: /tmp/kraft-combined-logs
      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: kafka-data
